name: ecosan
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  cloud_firestore_odm: ^1.0.0-dev.64
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  flutter:
    sdk: flutter
  get: 4.6.5
  google_fonts: ^5.1.0
  google_sign_in: ^6.1.4
  json_annotation: ^4.8.1
  cloud_firestore: ^4.8.4
  sizer: ^2.0.15
  flutter_svg: ^2.0.7
  glassmorphism: ^3.0.0
  camera: ^0.10.5+3
  syncfusion_flutter_charts: ^22.2.9
  accordion: ^2.5.1
  firebase_storage: ^11.2.6
  file_picker: ^5.3.3
  url_launcher: ^6.1.12

dev_dependencies:
  build_runner: ^2.4.6
  cloud_firestore_odm_generator: ^1.0.0-dev.58
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1

flutter:
  assets:
    - assets/images/
    - assets/images/payment/
    - assets/json/
    - assets/svgs/
    # - assets/icons/
  uses-material-design: true
