name: ecosan
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  accordion: ^2.5.1
  camera: ^0.10.5+3
  cloud_firestore: ^4.8.4
  cloud_firestore_odm: ^1.0.0-dev.64
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  file_picker: ^5.3.3
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  firebase_storage: ^11.2.6
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.3.2
  flutter_map: ^5.0.0
  flutter_svg: ^2.0.7
  geolocator: ^10.0.0
  get: 4.6.5
  glassmorphism: ^3.0.0
  google_fonts: ^5.1.0
  google_sign_in: ^6.1.4
  json_annotation: ^4.8.1
  latlong2: ^0.9.0
  sizer: ^2.0.15
  syncfusion_flutter_charts: ^22.2.9
  url_launcher: ^6.1.12
  vector_map_tiles: ^5.0.0

dev_dependencies:
  build_runner: ^2.4.6
  cloud_firestore_odm_generator: ^1.0.0-dev.58
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1

flutter:
  assets:
    - .env
    - assets/images/
    - assets/images/payment/
    - assets/json/
    - assets/svgs/
  uses-material-design: true

flutter_native_splash:
  color: '#ffffff'
  image: assets/images/Logo Samping.png

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/images/App Icon.png'
  web:
    generate: true
    image_path: 'assets/images/App Icon.png'
  windows:
    generate: true
    image_path: 'assets/images/App Icon.png'
  macos:
    generate: true
    image_path: 'assets/images/App Icon.png'
